<?php

/**
 * @author		Miguel Angel Macias Burgos
 * @company 	WBT
 * @copyright 	2026
 * @version     1.0
 */

set_time_limit(0);
//error_reporting(0);

require_once "Config.php";

class DataBase
{
    private $serverName = "localhost:3306";//:3308
    private $user = "root";
    private $pswd = "123456789";
    private $dbName = "pizzas1";
    
    private $link;
    private $op = 1; // 1: xamp, 2: easyphp
    
    function Open()
    {
        if ($this->op == 1){
            $this->link = mysqli_connect($this->serverName, $this->user, $this->pswd);
            mysqli_select_db($this->link, $this->dbName);
        }
        
        return $this->link;
    }
    
    /**
     * @return : true or false
     * */
    function Execute($_sql){
        if ($this->op == 1){
            $res = mysqli_query($this->link, $_sql);
        }
        
        return $res;
    }
    
    function GetLastIdAutoGenerated()
    {
        if ($this->op == 1){
            return mysqli_insert_id($this->link);
        }
    }
    
    function ContainsData($res)
    {
        $total = 0;
        if ($this->op == 1){
            $total = mysqli_num_rows($res);
        }
        
        if ($total > 0){
            return true;
        }else{
            return false;
        }
    }
    
    function DataListStructure($_res)
    {
    	$i=0;
	    $ret = array();
        
        if ($this->op == 1){
            while ($row = mysqli_fetch_assoc($_res)) {
    	        foreach ($row as $key => $value) {
    	            $ret[$i][$key] = $value;
    	            }
    	        $i++;
         	}
        }   
	    
	    return ($ret);	    
    }
    
    function FetchArray($_res){
        if ($this->op == 1){
            $array = mysqli_fetch_array($_res);
        }
        
        return $array;
    }
}

?>