<?php

require_once "data/Cliente.php";
require_once "data/DB.php";

class RN_Cliente extends DataBase{

	function __construct()
	{
		parent::Open();
	}

	function GetList(){
		$sql = "Select * from cliente where estado = 'Activo'";
		$res = $this->Execute($sql);
		
		$list = array();

		if ($this->ContainsData($res)){
			$data = $this->DataListStructure($res);
			foreach ($data as $item) {
				$list[] = new Cliente(
					$item["idCliente"],
					$item["hashCliente"],
					$item["nombre"],
					$item["telefono"],
					$item["direccion"],
					$item["estado"]
				);
			}
		}

		return $list;
	}

	function GetData($hashCliente){
		$sql = "Select * from cliente where hashCliente = '" . $hashCliente . "'";
		$res = $this->Execute($sql);
		
		$oCliente = null;

		if ($this->ContainsData($res)){
			$data = $this->DataListStructure($res);
			foreach ($data as $item) {
				$oCliente = new Cliente(
					$item["idCliente"],
					$item["hashCliente"],
					$item["nombre"],
					$item["telefono"],
					$item["direccion"],
					$item["estado"]
				);
			}
		}

		return $oCliente;
	}

	function Save($oCliente){
		$sql = "Insert into cliente values (0,
		'" . $oCliente->hashCliente . "',
		'" . $oCliente->nombre . "',
		'" . $oCliente->telefono . "',
		'" . $oCliente->direccion . "',
		'" . $oCliente->estado . "')";

		$res = $this->Execute($sql);
		$id = $this->GetLastIdAutoGenerated();

		$sql2 = "Update cliente set hashCliente = '" . sha1($id) . "' where idCliente = " . $id;
		$this->Execute($sql2);

		return $res;
	}

	function Update($oCliente){
		$sql = "Update cliente set
			nombre = '" . $oCliente->nombre . "',
			telefono = '" . $oCliente->telefono . "',
			direccion = '" . $oCliente->direccion . "',
			estado = '" . $oCliente->estado . "'
			where hashCliente = '" . $oCliente->hashCliente . "'";

		return $this->Execute($sql);
	}

	function Delete($hashCliente){
		$sql = "Update cliente set estado = 'Inactivo' where hashCliente = '" . $hashCliente . "'";
		return $this->Execute($sql);
	}
}

?>
