<?php

require_once "data/Perfil.php";
require_once "data/DB.php";

class RN_Perfil extends DataBase{

    function __construct()
    {
        parent::Open();
        // $this->Open();
    }

    function GetList(){
        $sql = "Select * from perfil";
        $res = $this->Execute($sql);
        
        $list = array();

        if ($this->ContainsData($res)){
            $data = $this->DataListStructure($res);
            foreach ($data as $item) {
                $list[] = new Perfil(
                    $item["idPerfil"],
                    $item["hashPerfil"],
                    $item["nombre"],
                    $item["descripcion"],
                    $item["estado"]
                );
            }
        }

        return $list;
    }

    function Save($oPerfil){
        // Aquí se implementaría la lógica para guardar el perfil
        $sql = "Insert into perfil values (0,
        '" . $oPerfil->hashPerfil . "',
        '" . $oPerfil->nombre . "',
        '" . $oPerfil->descripcion . "',
        '" . $oPerfil->estado . "')";

        $res = $this->Execute($sql);
        $id = $this->GetLastIdAutoGenerated();

        $sql2 = "Update perfil set hashPerfil = '" . sha1($id) . "' where idPerfil = " . $id;

        $this->Execute($sql2);

        return $res;
    }

    function Update($oPerfil){
        // Aquí se implementaría la lógica para actualizar el perfil
    }

    function Delete($hashPerfil){
        // Aquí se implementaría la lógica para eliminar el perfil
    }
}

?>