<?php

require_once "data/Tarifas.php";
require_once "data/DB.php";

class RN_Tarifas extends DataBase{

	function __construct()
	{
		parent::Open();
	}

	function GetList(){
		$sql = "Select * from tarifaentrega";
		$res = $this->Execute($sql);

		$list = array();

		if ($this->ContainsData($res)){
			$data = $this->DataListStructure($res);
			foreach ($data as $item) {
				$list[] = new Tarifas(
					$item["idTarifaEntrega"],
					$item["hashTarifaEntrega"],
					$item["zona"],
					$item["precioDelivery"],
					$item["estado"]
				);
			}
		}

		return $list;
	}

	function GetData($hashTarifaEntrega){
		$sql = "Select * from tarifaentrega where hashTarifaEntrega = '" . $hashTarifaEntrega . "'";
		$res = $this->Execute($sql);

		$oTarifa = null;

		if ($this->ContainsData($res)){
			$data = $this->DataListStructure($res);
			foreach ($data as $item) {
				$oTarifa = new Tarifas(
					$item["idTarifaEntrega"],
					$item["hashTarifaEntrega"],
					$item["zona"],
					$item["precioDelivery"],
					$item["estado"]
				);
			}
		}

		return $oTarifa;
	}

	function Save($oTarifa){
		$sql = "Insert into tarifaentrega values (0,
		'" . $oTarifa->hashTarifaEntrega . "',
		'" . $oTarifa->zona . "',
		'" . $oTarifa->precioDelivery . "',
		'" . $oTarifa->estado . "')";

		$res = $this->Execute($sql);
		$id = $this->GetLastIdAutoGenerated();

		$sql2 = "Update tarifaentrega set hashTarifaEntrega = '" . sha1($id) . "' where idTarifaEntrega = " . $id;
		$this->Execute($sql2);

		return $res;
	}

	function Update($oTarifa){
		$sql = "Update tarifaentrega set
				zona = '" . $oTarifa->zona . "',
				precioDelivery = '" . $oTarifa->precioDelivery . "',
				estado = '" . $oTarifa->estado . "'
				where hashTarifaEntrega = '" . $oTarifa->hashTarifaEntrega . "'";

		return $this->Execute($sql);
	}

	function Delete($hashTarifaEntrega){
		$sql = "Update tarifaentrega set estado = 'Inactivo' where hashTarifaEntrega = '" . $hashTarifaEntrega . "'";
		$res = $this->Execute($sql);
		return $res;
	}
}

?>
