<?php

require_once "data/TiposPizzas.php";
require_once "data/DB.php";

class RN_TiposPizzas extends DataBase{

	function __construct()
	{
		parent::Open();
	}

	function GetList(){
		$sql = "Select * from tipopizza";
		$res = $this->Execute($sql);

		$list = array();

		if ($this->ContainsData($res)){
			$data = $this->DataListStructure($res);
			foreach ($data as $item) {
				$list[] = new TiposPizzas(
					$item["idTipoPizza"],
					$item["hashTipoPizza"],
					$item["nombre"],
					$item["descripcion"],
					$item["imagen"],
					$item["estado"]
				);
			}
		}

		return $list;
	}

	function GetData($hashTipoPizza){
		$sql = "Select * from tipopizza where hashTipoPizza = '" . $hashTipoPizza . "'";
		$res = $this->Execute($sql);

		$oTipoPizza = null;

		if ($this->ContainsData($res)){
			$data = $this->DataListStructure($res);
			foreach ($data as $item) {
				$oTipoPizza = new TiposPizzas(
					$item["idTipoPizza"],
					$item["hashTipoPizza"],
					$item["nombre"],
					$item["descripcion"],
					$item["imagen"],
					$item["estado"]
				);
			}
		}

		return $oTipoPizza;
	}

	function Save($oTipoPizza){
		$sql = "Insert into tipopizza values (0,
		'" . $oTipoPizza->hashTipoPizza . "',
		'" . $oTipoPizza->nombre . "',
		'" . $oTipoPizza->descripcion . "',
		'" . $oTipoPizza->imagen . "',
		'" . $oTipoPizza->estado . "')";

		$res = $this->Execute($sql);
		$id = $this->GetLastIdAutoGenerated();

		$sql2 = "Update tipopizza set hashTipoPizza = '" . sha1($id) . "' where idTipoPizza = " . $id;
		$this->Execute($sql2);

		return $res;
	}

	function Update($oTipoPizza){
		$sql = "Update tipopizza set
				nombre = '" . $oTipoPizza->nombre . "',
				descripcion = '" . $oTipoPizza->descripcion . "',
				imagen = '" . $oTipoPizza->imagen . "',
				estado = '" . $oTipoPizza->estado . "'
				where hashTipoPizza = '" . $oTipoPizza->hashTipoPizza . "'";

		return $this->Execute($sql);
	}

	function Delete($hashTipoPizza){
		$sql = "Update tipopizza set estado = 'Inactivo' where hashTipoPizza = '" . $hashTipoPizza . "'";
		$res = $this->Execute($sql);
		return $res;
	}
}

?>
