<?php

require_once "data/Tamanho.php";
require_once "data/DB.php";

class RN_Tamanho extends DataBase{

	function __construct()
	{
		parent::Open();
	}

	function GetList(){
		$sql = "Select * from tamanho";
		$res = $this->Execute($sql);

		$list = array();

		if ($this->ContainsData($res)){
			$data = $this->DataListStructure($res);
			foreach ($data as $item) {
				$list[] = new Tamanho(
					$item["idTamanho"],
					$item["hashTamanho"],
					$item["nombre"],
					$item["precio"],
					$item["estado"]
				);
			}
		}

		return $list;
	}

	function GetData($hashTamanho){
		$sql = "Select * from tamanho where hashTamanho = '" . $hashTamanho . "'";
		$res = $this->Execute($sql);

		$oTamanho = null;

		if ($this->ContainsData($res)){
			$data = $this->DataListStructure($res);
			foreach ($data as $item) {
				$oTamanho = new Tamanho(
					$item["idTamanho"],
					$item["hashTamanho"],
					$item["nombre"],
					$item["precio"],
					$item["estado"]
				);
			}
		}

		return $oTamanho;
	}

	function Save($oTamanho){
		$sql = "Insert into tamanho values (0,
		'" . $oTamanho->hashTamanho . "',
		'" . $oTamanho->nombre . "',
		'" . $oTamanho->precio . "',
		'" . $oTamanho->estado . "')";

		$res = $this->Execute($sql);
		$id = $this->GetLastIdAutoGenerated();

		$sql2 = "Update tamanho set hashTamanho = '" . sha1($id) . "' where idTamanho = " . $id;
		$this->Execute($sql2);

		return $res;
	}

	function Update($oTamanho){
		$sql = "Update tamanho set
				nombre = '" . $oTamanho->nombre . "',
				precio = '" . $oTamanho->precio . "',
				estado = '" . $oTamanho->estado . "'
				where hashTamanho = '" . $oTamanho->hashTamanho . "'";

		return $this->Execute($sql);
	}

	function Delete($hashTamanho){
		$sql = "Update tamanho set estado = 'Inactivo' where hashTamanho = '" . $hashTamanho . "'";
		$res = $this->Execute($sql);
		return $res;
	}
}

?>
