<?php

require_once "data/Usuario.php";
require_once "data/DB.php";

class RN_Usuario extends DataBase{

    function __construct()
    {
        parent::Open();
        // $this->Open();
    }

    function GetList(){
        $sql = "Select * from usuario";
        $res = $this->Execute($sql);
        
        $list = array();

        if ($this->ContainsData($res)){
            $data = $this->DataListStructure($res);
            foreach ($data as $item) {
                $list[] = new Usuario(
                    $item["idUsuario"],
                    $item["hashUsuario"],
                    $item["nombre"],
                    $item["username"],
                    $item["pswd"],
                    $item["idPerfil"],
                    $item["estado"]
                );
            }
        }

        return $list;
    }

    function GetData($hashUsuario){
        $sql = "Select *, AES_DECRYPT(pswd, '" . UK . "') as pswd_2 
                from usuario
                where hashUsuario = '" . $hashUsuario . "'";
        $res = $this->Execute($sql);
        
        $oUsuario = null;

        if ($this->ContainsData($res)){
            $data = $this->DataListStructure($res);
            foreach ($data as $item) {
                $oUsuario = new Usuario(
                    $item["idUsuario"],
                    $item["hashUsuario"],
                    $item["nombre"],
                    $item["username"],
                    $item["pswd_2"],
                    $item["idPerfil"],
                    $item["estado"]
                );
            }
        }

        return $oUsuario;
    }

    function Save($oUsuario){
        // Aquí se implementaría la lógica para guardar el usuario
        $sql = "Insert into usuario values (0,
        '" . $oUsuario->hashUsuario . "',
        '" . $oUsuario->nombre . "',
        '" . $oUsuario->username . "',
        AES_ENCRYPT('" . $oUsuario->pswd . "', '" . UK . "'),
        '" . $oUsuario->idPerfil . "',
        '" . $oUsuario->estado . "')";

        $res = $this->Execute($sql);
        $id = $this->GetLastIdAutoGenerated();

        $sql2 = "Update usuario set hashUsuario = '" . sha1($id) . "' where idUsuario = " . $id;

        $this->Execute($sql2);

        return $res;
    }

    function Update($oUsuario){
        // Aquí se implementaría la lógica para actualizar el usuario
    }

    function Delete($hashUsuario){
        // Aquí se implementaría la lógica para eliminar el usuario
    }

    function Verificar($_username, $_pswd){
        $sql = "Select * 
                from usuario
                where username = '" . $_username . "' and
                pswd = AES_ENCRYPT('" . $_pswd . "', '" . UK . "')";
        $res = $this->Execute($sql);

        if ($this->ContainsData($res)){
            $row = $this->FetchArray($res);
            $hashUsuario = $row["hashUsuario"];
            return $hashUsuario;
        }

        return false;
    }
}

?>