<?php

require_once "data/Venta.php";
require_once "data/DB.php";

class RN_Venta extends DataBase{

	function __construct()
	{
		parent::Open();
	}

	function GetList(){
		$sql = "Select * from venta where estado = 'Activo'";
		$res = $this->Execute($sql);
		
		$list = array();

		if ($this->ContainsData($res)){
			$data = $this->DataListStructure($res);
			foreach ($data as $item) {
				$list[] = new Venta(
					$item["idVenta"],
					$item["hashVenta"],
					$item["fechaVenta"],
					$item["horaVenta"],
					$item["total"],
					$item["idCliente"],
					$item["idUsuario"],
					$item["idTarifaEntrega"],
					$item["observacion"],
					$item["estado"]
				);
			}
		}

		return $list;
	}

	function GetData($hashVenta){
		$sql = "Select * from venta where hashVenta = '" . $hashVenta . "'";
		$res = $this->Execute($sql);
		
		$oVenta = null;

		if ($this->ContainsData($res)){
			$data = $this->DataListStructure($res);
			foreach ($data as $item) {
				$oVenta = new Venta(
					$item["idVenta"],
					$item["hashVenta"],
					$item["fechaVenta"],
					$item["horaVenta"],
					$item["total"],
					$item["idCliente"],
					$item["idUsuario"],
					$item["idTarifaEntrega"],
					$item["observacion"],
					$item["estado"]
				);
			}
		}

		return $oVenta;
	}

	function Save($oVenta){
		$sql = "Insert into venta values (0,
		'" . $oVenta->hashVenta . "',
		'" . $oVenta->fechaVenta . "',
		'" . $oVenta->horaVenta . "',
		'" . $oVenta->total . "',
		" . $oVenta->idCliente . ",
		" . $oVenta->idUsuario . ",
		" . $oVenta->idTarifaEntrega . ",
		'" . $oVenta->observacion . "',
		'" . $oVenta->estado . "')";

		$res = $this->Execute($sql);
		$id = $this->GetLastIdAutoGenerated();
		$sql2 = "Update venta set hashVenta = '" . sha1($id) . "' where idVenta = " . $id;
		$this->Execute($sql2);
		return $id;
	}

	function Update($oVenta){
		$sql = "Update venta set
			total = '" . $oVenta->total . "',
			idCliente = " . $oVenta->idCliente . ",
			idTarifaEntrega = " . $oVenta->idTarifaEntrega . ",
			observacion = '" . $oVenta->observacion . "'
			where hashVenta = '" . $oVenta->hashVenta . "'";

		return $this->Execute($sql);
	}

	function Delete($hashVenta){
		$sql = "Update venta set estado = 'Inactivo' where hashVenta = '" . $hashVenta . "'";
		return $this->Execute($sql);
	}
}

?>
