<?php

require_once __DIR__ . "/../data/DB.php";

class ChatModelo extends DataBase
{
    function ObtenerConversacion($clienteCi, $adminUsuario)
    {
        $sql = "SELECT id FROM Conversacion 
               WHERE cliente_ci = '$clienteCi' AND admin_usuario = '$adminUsuario' AND estado = 'activa'
               ORDER BY fechaInicio DESC LIMIT 1";
        $res = $this->Execute($sql);
        if ($this->ContainsData($res)) {
            $row = $this->FetchArray($res);
            return $row['id'];
        }
        return null;
    }

    function CrearConversacion($clienteCi, $adminUsuario)
    {
        $sql = "INSERT INTO Conversacion (cliente_ci, admin_usuario) VALUES ('$clienteCi', '$adminUsuario')";
        $this->Execute($sql);
        return $this->GetLastIdAutoGenerated();
    }

    function ObtenerOMostarCrearConversacion($clienteCi, $adminUsuario)
    {
        $id = $this->ObtenerConversacion($clienteCi, $adminUsuario);
        if (!$id) {
            $id = $this->CrearConversacion($clienteCi, $adminUsuario);
        }
        return $id;
    }

    function EnviarMensaje($conversacionId, $remitente, $tipo, $contenido)
    {
        $sql = "INSERT INTO Mensaje (conversacion_id, remitente, tipo, contenido) 
               VALUES ($conversacionId, '$remitente', '$tipo', '$contenido')";
        return $this->Execute($sql);
    }

    function ObtenerMensajes($conversacionId, $desdeId = 0)
    {
        $sql = "SELECT id, remitente, tipo, contenido, leido, fechaHora 
               FROM Mensaje 
               WHERE conversacion_id = $conversacionId AND id > $desdeId
               ORDER BY fechaHora ASC";
        $res = $this->Execute($sql);
        return $this->DataListStructure($res);
    }

    function MarcarLeidos($conversacionId, $remitente)
    {
        $sql = "UPDATE Mensaje SET leido = 1 
                WHERE conversacion_id = $conversacionId AND remitente != '$remitente' AND leido = 0";
        return $this->Execute($sql);
    }

    function getMensajesCount($conversacionId)
    {
        $sql = "SELECT COUNT(*) as total FROM Mensaje WHERE conversacion_id = $conversacionId";
        $res = $this->Execute($sql);
        $row = $this->FetchArray($res);
        return $row['total'];
    }
}